# generated by Git for Windows
test -f ~/.profile && . ~/.profile
# test -f ~/.bashrc && . ~/.bashrc # this will cause .bashrc to load twice (win11)

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
